name: CI/CD for flexify-ui

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published] # Trigger CI/CD on published releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the library
        run: npm run build

      - name: Run tests
        run: npm run test

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check all secrets
        run: |
          echo "Checking all secrets..."
          
          # Check if NPM_TOKEN exists
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN is NOT available!"
          else
            echo "NPM_TOKEN is available!"
          fi
          
          # Check if GITHUB_TOKEN exists
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "GITHUB_TOKEN is NOT available!"
          else
            echo "GITHUB_TOKEN is available!"
          fi

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish --access public

      - name: Create a release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
