name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.0.0, v2.1.0, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js with version 18
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js version 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional, can be skipped or customized)
      - name: Run tests
        run: npm test

      # Step 5: Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Fetch NPM_TOKEN from GitHub Secrets

      # Step 6: Create GitHub Release
      - name: Create Release
        uses: gh-actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 'Automated release via GitHub Actions'
          draft: false
          prerelease: false
